---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: customer
  name: customer
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    run: customer
  type: NodePort

